### ISSUE TITLE
Seeing a lot of chat re-broadcasting after July 4th weekend

### ISSUE THREAD

**Issue by kontu** [Bishbash777/SEDB-RELOADED#10]
Not sure if Discord changed something, but since the weekend we've been seeing SEDB re-broadcast messages from other servers randomly. This is most notable around during server restart time. Nothing has changed in our configs (I triple checked and compared to backups from a couple weeks ago to be sure)

https://i.imgur.com/akvBp5z.png

If we have the Status channel ID set the same as the chat channel ID it's *really* bad with restarts, as all servers rebroadcast the "Server stopped" and "Server Started" messages for all others and we get super bad spam from it.
https://i.imgur.com/GcLZqqs.png
```
<?xml version="1.0" encoding="utf-8"?>
<SEDBConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Enabled>true</Enabled>
  <PreLoad>true</PreLoad>
  <Embed>true</Embed>
  <DisplaySteamId>false</DisplaySteamId>
  <BotToken>REDACTED</BotToken>
  <ChatChannelId>594078575682912256</ChatChannelId>
  <Format>{p}: {msg}</Format>
  <Format2>{p}</Format2>
  <CommandChannelId>595131449255002117</CommandChannelId>
  <CommandPrefix>&lt;&lt;</CommandPrefix>
  <AsServer>false</AsServer>
  <UseNicks>false</UseNicks>
  <BotToGame>true</BotToGame>
  <ServerToDiscord>true</ServerToDiscord>
  <ServerName>Theta Draconis</ServerName>
  <StatusChannelId>730008957644439583</StatusChannelId>
  <Started>:white_check_mark: [Lambda Draconis] Server Started!</Started>
  <Stopped>:x: [Lambda Draconis] Server Stopped!</Stopped>
  <Connect />
  <Join />
  <Leave />
  <SimPing>false</SimPing>
  <SimChannel />
  <SimThresh>0.60</SimThresh>
  <SimMessage>@here Simulation speed has dropped below threshold!</SimMessage>
  <SimCooldown>1200</SimCooldown>
  <UseStatus>true</UseStatus>
  <StatusInterval>5000</StatusInterval>
  <StatusPre>Server Starting...</StatusPre>
  <Status>{p} players | SS {ss}</Status>
  <MentOthers>true</MentOthers>
  <MentEveryone>false</MentEveryone>
  <TokenVisibleState>Visible</TokenVisibleState>
  <RemoveResponse>0</RemoveResponse>
  <FactionChannels />
  <GlobalColor>Debug</GlobalColor>
  <FacColor>White</FacColor>
  <FacFormat>{p}: {msg}</FacFormat>
  <FacFormat2>[FAC] {p}</FacFormat2>
  <CommandPerms />
</SEDBConfig>
```

**Comment by kontu** [comment]
Seems primarily focused around restart times

**Comment by Bishbash777** [comment]
I believe this may be at fault by the retry logic i built into SEDB if a message fails to send to discord. Please can you attach our torch log file for the date this occurs

**Comment by kontu** [comment]
[torch_sedb_issue.log](https://github.com/Bishbash777/SEDB-RELOADED/files/4903033/torch_sedb_issue.log)

Let me know if you need more logs, I just grabbed one from one of the 8 servers.

**Comment by kontu** [comment]
So if we disable "Load bot before start" it cuts down on 99% of the spam. It's always during server start that it occurs.

**Comment by protectedsnow** [comment]
pls close this
as far I tested and seen all works to be fine in v2 version

**Comment by kontu** [comment]
We still see this in v2.0.2.5. To a lesser extreme, but definitely still see this.

**Comment by protectedsnow** [comment]
mystery bug
ok
how I said in
https://github.com/Bishbash777/SEDB-RELOADED/issues/6#issuecomment-746350665
try 2.0.2.4 
on most servers who tryed use latest version, I seen same issues.
