### ISSUE TITLE
Feature Request: Group Command

### ISSUE THREAD

**Issue by Youfoundme001** [Bishbash777/SEDB-RELOADED#12]
Bishbash,

I wanted to see if you could integrate a way to send 1 command to multiple instances of SEDB.  Currently we have to type out a command with a new <prefix> for each server.  Is this something that could be implemented or is it possible to have the SEDB read input from other bots?  (IE: turn of ignore message from other bots)?

Thank you!
YouFoundMe

**Comment by Bishbash777** [comment]
Hello! This is already possible :) just add another command channel ID to the config field, separated by space
