### ISSUE TITLE
Notify a discord role of server sim

### ISSUE THREAD

**Issue by bodyboarder2528** [Bishbash777/SEDB-RELOADED#14]
currently it wont notify a discord role but a player it will

**Comment by bodyboarder2528** [comment]
hey how is this looking Bish?

**Comment by protectedsnow** [comment]
maybe I'll fix this in current year.
as far I know you can use <!role-id> for ping role or user

**Comment by bodyboarder2528** [comment]
With no @

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bodyboarder2528** [comment]
so i found out to ping a role its <!&roleID> and its the & thats fucking with it.

**Comment by Bishbash777** [comment]
Fixed in upcoming update
