### ISSUE TITLE
Player able to ping @everyone from in game even though that feature is unchecked

### ISSUE THREAD

**Issue by kontu** [Bishbash777/SEDB-RELOADED#20]
https://i.imgur.com/4TkrfDL.png
Definitely pinged everyone
https://i.imgur.com/TGw7ORJ.png

**Comment by protectedsnow** [comment]
pls add checks for config 
https://github.com/Bishbash777/SEDB-RELOADED/blob/d958b819b4080062b1d4dc5d8edf1b62e4fe4538/SEDiscordBridge/DiscordBridge.cs#L166
