### ISSUE TITLE
Ability to prevent server messages for faction chat

### ISSUE THREAD

**Issue by bodyboarder2528** [Bishbash777/SEDB-RELOADED#30]
![image](https://user-images.githubusercontent.com/49468427/112592609-5a698e00-8e5a-11eb-8ba3-b89d6055188a.png)

**Comment by bodyboarder2528** [comment]
To reproduce set it up as per normal for faction chat on each sector then send a message. its a issue with global chat but changing servertodiscord as false u dont have a issue. This is because casimir uses server messages to link servers

**Comment by Bishbash777** [comment]
Fixed in upcoming update
