### ISSUE TITLE
One-way messaging after update

### ISSUE THREAD

**Issue by BartekSz95** [Bishbash777/SEDB-RELOADED#33]
Version: **2.0.2.8**
After update stops working sending messaging from in-game global chat and faction chats to Discord's channels. Only option to force this is ticking _Server outputs to Discord_, but this spamming Discord with server notifications.

![IMG_20210406_091500](https://user-images.githubusercontent.com/79801491/113678452-eaab9c80-96be-11eb-87d2-c5004ea92cfe.jpg)
![unknown](https://user-images.githubusercontent.com/79801491/113678455-ebdcc980-96be-11eb-82d0-03591493c506.png)

**Comment by Bishbash777** [comment]
Fixed in latest update
