### ISSUE TITLE
Chat from Discord to in game chat is blank in game and within console (to [Null]): 

### ISSUE THREAD

**Issue by Drakcore** [Bishbash777/SEDB-RELOADED#48]
Messages from discord to SE just end up being blank (just the username appears)
In the Torch console you see the same results but instead of the blank text you get (to [Null]}
Text from with SE goes smoothly to the Discord channel and people who reply to that message have their message replicated to the SE chat as if they only taking and not directed at someone.

Attached image is of 3 chats, first being form SE to Discord, second a reply to that bot replicated message in discord and the last example is a direct message from discord to SE.
![discord to SE](https://user-images.githubusercontent.com/113472898/189999538-db3b9362-79dd-4f73-8e95-bfebd498159d.jpg)

Here is the config minus the bot token.
`<SEDBConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Enabled>true</Enabled>
  <PreLoad>true</PreLoad>
  <LoadRanks>false</LoadRanks>
  <Embed>false</Embed>
  <DisplaySteamId>false</DisplaySteamId>
  <BotToken>lehbottoken</BotToken>
  <ChatChannelId>1018309476505354270</ChatChannelId>
  <Format>[THANATOS]: **{p}**: {msg}</Format>
  <Format2>[D]{p}</Format2>
  <CommandChannelId />
  <CommandPrefix>;;</CommandPrefix>
  <AsServer>false</AsServer>
  <UseNicks>false</UseNicks>
  <BotToGame>false</BotToGame>
  <ServerToDiscord>false</ServerToDiscord>
  <ServerName>Server</ServerName>
  <StatusChannelId>1018335009448398918</StatusChannelId>
  <Started>:white_check_mark: Server Started!</Started>
  <Stopped>:x: Server Stopped!</Stopped>
  <Restarted>:arrows_counterclockwise: Server Go To Restart!</Restarted>
  <StripGPS>false</StripGPS>
  <Connect>:key: The player {p} connected to server</Connect>
  <Join>:sunny: The player {p} joined the server</Join>
  <Leave>:new_moon: The player {p} left the server</Leave>
  <SimPing>true</SimPing>
  <SimChannel>1018335009448398918</SimChannel>
  <SimThresh>0.5</SimThresh>
  <SimMessage>@here Simulation speed has dropped below threshold!</SimMessage>
  <SimCooldown>1200</SimCooldown>
  <UseStatus>true</UseStatus>
  <StatusInterval>5000</StatusInterval>
  <StatusPre>Server Starting...</StatusPre>
  <Status>{p} players | SS {ss}</Status>
  <MentOthers>true</MentOthers>
  <MentEveryone>false</MentEveryone>
  <TokenVisibleState>Visible</TokenVisibleState>
  <RemoveResponse>30</RemoveResponse>
  <FactionChannels />
  <GlobalColor>White</GlobalColor>
  <FacColor>Green</FacColor>
  <FacFormat>:ledger: **{p}**: {msg}</FacFormat>
  <FacFormat2>[D-Fac]{p}</FacFormat2>
  <CommandPerms />
</SEDBConfig>`

**Comment by stiderspace** [comment]
Having the same problem any messages send normally won’t go through.

Replying to a message from the server does work, but any other message from discord just shows a blank message in the server

**Comment by Drakcore** [comment]
> Having the same problem any messages send normally won’t go through.
> 
> Replying to a message from the server does work, but any other message from discord just shows a blank message in the server

Figured it out when I looked at the other issue. It is just a permission issue and options for the bot. Just check the following if they are enabled for the bot.
Make sure "MESSAGE CONTENT INTENT" is enabled.
Don't think "PRESENCE INTENT" is needed but I also enabled it for good measure, after which direct text in that chat and not just replies gets replicated now back to the in game chat.

![image](https://user-images.githubusercontent.com/113472898/190515232-5db559b4-473b-4490-af77-11bb3b4885fb.png)

**Comment by Drakcore** [comment]
@stiderspace  Give it a try yourself and then close the ticket with a comment/response.

**Comment by IBlackjk** [comment]
I have had the same Problem. Enabling this stuff did the Trrick now it works thanks!

**Comment by stiderspace** [comment]
@Drakcore Yep that did the trick thanks for the explaination

**Comment by Drakcore** [comment]
Closing.
