### ISSUE TITLE
Feature request : Ability to have a second commands channel and prefix

### ISSUE THREAD

**Issue by kontu** [Bishbash777/SEDB-RELOADED#5]
Ok so...
We have 10 torch instances we administer. We use Discord commands to manage a lot of it.
Often we need to run the same command on all 10 instances. Right now that means entering the command 10 times, with a different prefix for each server

It would be awesome if there was a way to have a second channel ID for commands as well as a second prefix so that we could basically have a "apply to all instances" prefix/channel for these mass commands instead of having to enter it in ten times

Anyone administering multiple servers could benefit from this

**Comment by Bishbash777** [comment]
Added ability for multiple command channels
